application: iss-flasktest-shopshape
version: py1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: app.app

libraries:
- name: PIL
  version: latest
- name: jinja2
  version: latest

- name: webapp2
  version: "2.5.2"


builtins:
- appstats: on