application: iss-dev-shopshape
version: py1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: PIL
  version: latest
- name: jinja2
  version: latest

builtins:
- appstats: on